<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\TransportOffer;
use App\Models\TransportRequest;
use App\Models\Vehicle;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
class TransporterController extends Controller
{
 private function transporter(Request $request): void { abort_unless($request->user()?->user_type === 'transporteur', 403); }
 public function vehicles(Request $request): JsonResponse { $this->transporter($request); return response()->json(['data'=>$request->user()->vehicles()->latest()->get()]); }
 public function storeVehicle(Request $request): JsonResponse { $this->transporter($request); $v=$request->validate(['vehicle_type'=>['required','string','max:100'],'brand'=>['required','string','max:100'],'registration'=>['required','string','max:40'],'capacity_tonnes'=>['required','numeric','gt:0'],'available_volume_m3'=>['nullable','numeric','gt:0'],'accepted_cargo_type'=>['required','string','max:120'],'is_available'=>['sometimes','boolean']]); $vehicle=$request->user()->vehicles()->create($v); return response()->json(['message'=>'Véhicule enregistré.','data'=>$vehicle],201); }
 public function updateVehicle(Request $request, Vehicle $vehicle): JsonResponse { $this->transporter($request); abort_unless($vehicle->user_id===$request->user()->id,404); $v=$request->validate(['vehicle_type'=>['required','string','max:100'],'brand'=>['required','string','max:100'],'registration'=>['required','string','max:40'],'capacity_tonnes'=>['required','numeric','gt:0'],'available_volume_m3'=>['nullable','numeric','gt:0'],'accepted_cargo_type'=>['required','string','max:120'],'is_available'=>['required','boolean']]); $vehicle->update($v); return response()->json(['data'=>$vehicle->fresh()]); }
 public function offers(Request $request): JsonResponse { $this->transporter($request); return response()->json(['data'=>$request->user()->transportOffers()->with('vehicle')->latest()->get()]); }
 public function storeOffer(Request $request): JsonResponse { $this->transporter($request); $v=$request->validate(['vehicle_id'=>['required','integer','exists:vehicles,id'],'departure'=>['required','string','max:120'],'destination'=>['required','string','max:120','different:departure'],'offer_date'=>['required','date','after_or_equal:today'],'capacity_tonnes'=>['required','numeric','gt:0'],'available_capacity_tonnes'=>['required','numeric','gt:0'],'accepted_cargo_type'=>['required','string','max:120'],'pricing_mode'=>['required',Rule::in(['forfait','tonne'])],'price_amount'=>['nullable','numeric','gte:0','required'],'additional_information'=>['nullable','string','max:5000']]); $vehicle=$request->user()->vehicles()->findOrFail($v['vehicle_id']); if((float)$v['capacity_tonnes']>(float)$vehicle->capacity_tonnes || (float)$v['available_capacity_tonnes']>(float)$v['capacity_tonnes']) return response()->json(['message'=>'Les capacités de l’offre sont incompatibles avec le véhicule.'],422); $offer=$request->user()->transportOffers()->create($v); return response()->json(['message'=>'Offre de transport publiée.','data'=>$offer->load('vehicle')],201); }
 public function updateOffer(Request $request, TransportOffer $transportOffer): JsonResponse { $this->transporter($request); abort_unless($transportOffer->user_id===$request->user()->id,404); $v=$request->validate(['departure'=>['required','string','max:120'],'destination'=>['required','string','max:120','different:departure'],'offer_date'=>['required','date','after_or_equal:today'],'capacity_tonnes'=>['required','numeric','gt:0'],'available_capacity_tonnes'=>['required','numeric','gt:0'],'accepted_cargo_type'=>['required','string','max:120'],'pricing_mode'=>['required',Rule::in(['forfait','tonne'])],'price_amount'=>['nullable','numeric','gte:0','required'],'additional_information'=>['nullable','string','max:5000'],'status'=>['required',Rule::in(['active','inactive'])]]); if((float)$v['available_capacity_tonnes']>(float)$v['capacity_tonnes']) return response()->json(['message'=>'La capacité disponible ne peut pas dépasser la capacité publiée.'],422); $transportOffer->update($v); return response()->json(['data'=>$transportOffer->fresh()->load('vehicle')]); }
 public function matches(Request $request, TransportRequest $transportRequest): JsonResponse { abort_unless($transportRequest->user_id===$request->user()->id,404); $weight=(float)$transportRequest->weight_kg/1000; $offers=TransportOffer::with(['vehicle','user'])->where('status','active')->whereDate('offer_date',$transportRequest->desired_date)->where('departure',$transportRequest->departure)->where('destination',$transportRequest->destination)->where('available_capacity_tonnes','>=',$weight)->whereHas('vehicle',fn($q)=>$q->where('is_available',true))->orderByDesc('available_capacity_tonnes')->get()->filter(function(TransportOffer $offer) use($transportRequest){$a=mb_strtolower(trim($offer->accepted_cargo_type));$r=mb_strtolower(trim($transportRequest->cargo_type));return in_array($a,['tous','toutes','general','général','marchandise','marchandises'],true)||$a===$r;})->values(); return response()->json(['data'=>$offers,'criteria'=>['departure'=>$transportRequest->departure,'destination'=>$transportRequest->destination,'date'=>$transportRequest->desired_date->toDateString(),'required_capacity_tonnes'=>$weight]]); }
}
